In [8]:
from urllib.request import urlretrieve
import pyreadr

url = (
    "https://raw.githubusercontent.com/genomicsclass/"
    "GSE5859Subset/master/data/GSE5859Subset.rda"
)

urlretrieve(url, "gene_expression.rda")

data = pyreadr.read_r("gene_expression.rda")

print(data.keys())

odict_keys(['geneExpression', 'sampleInfo', 'geneAnnotation'])

In [9]:
%pip install pyreadr

Requirement already satisfied: pyreadr in c:\users\fatin\desktop\python practice\python genetics project\gene expression explorer\.venv\lib\site-packages (0.5.7)
Requirement already satisfied: narwhals>=2.10.1 in c:\users\fatin\desktop\python practice\python genetics project\gene expression explorer\.venv\lib\site-packages (from pyreadr) (2.27.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\fatin\desktop\python practice\python genetics project\gene expression explorer\.venv\lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in c:\users\fatin\desktop\python practice\python genetics project\gene expression explorer\.venv\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\fatin\desktop\python practice\python genetics project\gene expression explorer\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\fatin\desktop\python practice\python genetics project\gene expression explorer\.venv\lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in c:\users\fatin\desktop\python practice\python genetics project\gene expression explorer\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
url = (
    "https://raw.githubusercontent.com/genomicsclass/"
    "GSE5859Subset/master/data/GSE5859Subset.rda"
)

In [12]:
# Berapa sampel bagi setiap kategori?
print(samples["ethnicity"].value_counts())

# Tengok hubungan label group dengan ethnicity
print(samples.groupby(["group", "ethnicity"]).size())

# Pastikan susunan sampel sama dalam kedua-dua jadual
matched = expression.columns.tolist() == samples["filename"].tolist()
print("Susunan sampel sepadan:", matched)

ethnicity
ASN    23
CEU     1
Name: count, dtype: int64
group  ethnicity
0.0    ASN          11
       CEU           1
1.0    ASN          12
dtype: int64
Susunan sampel sepadan: True

In [13]:
expression = data["geneExpression"]
samples = data["sampleInfo"]

print("Expression — baris, columns:", expression.shape)
display(expression.head())

print("Maklumat sampel:")
display(samples.head())

Expression — baris, columns: (8793, 24)

,GSM136508.CEL.gz,GSM136530.CEL.gz,GSM136517.CEL.gz,GSM136576.CEL.gz,GSM136566.CEL.gz,GSM136574.CEL.gz,GSM136575.CEL.gz,GSM136569.CEL.gz,GSM136568.CEL.gz,GSM136559.CEL.gz,...,GSM136727.CEL.gz,GSM136510.CEL.gz,GSM136515.CEL.gz,GSM136522.CEL.gz,GSM136507.CEL.gz,GSM136524.CEL.gz,GSM136514.CEL.gz,GSM136563.CEL.gz,GSM136564.CEL.gz,GSM136572.CEL.gz
1007_s_at,6.543954,6.401470,6.298943,6.837899,6.470689,6.450220,6.052854,6.387026,6.640583,6.948474,...,6.133068,6.502051,6.331567,6.354293,6.517539,6.156754,6.037871,6.639091,6.393338,6.469794
1053_at,7.546708,7.263547,7.201699,7.052761,6.980207,7.096195,6.983827,7.060558,7.010453,6.775048,...,7.280781,7.302209,7.456509,7.282859,7.689282,7.491967,7.413133,7.028731,6.697240,7.092346
117_at,5.402622,5.050546,5.024917,5.304313,5.214149,5.173731,5.022882,5.175134,5.281784,5.309194,...,5.401876,5.395087,5.280535,4.986950,5.562001,5.039387,5.054133,5.361298,5.218937,5.340272
121_at,7.892544,7.707754,7.461886,7.558130,7.819013,7.641136,7.729267,7.700608,7.615513,7.992304,...,7.607461,7.993732,7.632947,7.706585,7.612557,7.543667,7.507113,7.798197,7.976375,7.753480
1255_g_at,3.242779,3.222804,3.185605,3.195363,3.251915,3.324934,3.088541,3.184015,3.076940,3.167413,...,3.225123,3.440186,3.185090,3.192436,3.107306,3.128269,3.085953,3.174794,3.409032,3.274033

Maklumat sampel:

  ethnicity        date          filename  group
0       ASN  2005-06-23  GSM136508.CEL.gz    1.0
1       ASN  2005-06-27  GSM136530.CEL.gz    1.0
2       ASN  2005-06-27  GSM136517.CEL.gz    1.0
3       ASN  2005-10-28  GSM136576.CEL.gz    1.0
4       ASN  2005-10-07  GSM136566.CEL.gz    1.0